export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOG_OUT = "LOG_OUT"
export const LOAD_PROFILE = "LOAD_PROFILE"


export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"

export const SEARCHED_VIDEOS_SUCCESS = "SEARCHED_VIDEOS_SUCCESS"
export const SEARCHED_VIDEOS_FAIL = "SEARCHED_VIDEOS_FAIL"
export const SEARCHED_VIDEOS_REQUEST = "SEARCHED_VIDEOS_REQUEST"

export const SET_CURRENTVIDEO = "SET_CURRENTVIDEO"



export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE"
export const SIDEBAR_CHANGE_TYPE = "SIDEBAR_CHANGE_TYPE"
export const SIDEBAR_SETMENUITEM = "SIDEBAR_SETMENUITEM"